// Code generated by pioasm; DO NOT EDIT.

package ili9488

import "seedhammer.com/driver/pio"

const pioCyclesPerWrite = 2

var waitForVSYNCInst = uint32(ili9488_utilInstructions[0])

// ili9488

const ili9488WrapTarget = 0
const ili9488Wrap = 1

var ili9488Instructions = []uint16{
	//     .wrap_target
	0x98e0, //  0: pull   ifempty block   side 1
	0x7008, //  1: out    pins, 8         side 0
	//     .wrap
}

const ili9488Origin = -1

func ili9488ProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+ili9488WrapTarget, offset+ili9488Wrap)
	cfg.SetSidesetParams(2, true, false)
	return cfg
}

// ili9488_util

const ili9488_utilWrapTarget = 0
const ili9488_utilWrap = 0

var ili9488_utilInstructions = []uint16{
	//     .wrap_target
	0x20a0, //  0: wait   1 pin, 0
	//     .wrap
}

const ili9488_utilOrigin = -1

func ili9488_utilProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+ili9488_utilWrapTarget, offset+ili9488_utilWrap)
	cfg.SetSidesetParams(2, true, false)
	return cfg
}
