// Code generated by seedhammer.com/cmd/vectorfont; DO NOT EDIT.
package constant

import (
	_ "embed"
	"seedhammer.com/font/vector"
	"unsafe"
)

var Font = vector.NewFace(unsafe.Slice(unsafe.StringData(constantData), len(constantData)))

//go:embed constant.bin
var constantData string
