// Code generated by pioasm; DO NOT EDIT.

package tmc2209

import "seedhammer.com/driver/pio"

// uart_rx

const uart_rxWrapTarget = 0
const uart_rxWrap = 8

const uart_rxErrIRQ = 0

var uart_rxInstructions = []uint16{
	//     .wrap_target
	0x2020, //  0: wait   0 pin, 0
	0xea27, //  1: set    x, 7                   [10]
	0x4001, //  2: in     pins, 1
	0x0642, //  3: jmp    x--, 2                 [6]
	0x00c8, //  4: jmp    pin, 8
	0xc010, //  5: irq    nowait 0 rel
	0x20a0, //  6: wait   1 pin, 0
	0x0000, //  7: jmp    0
	0x8020, //  8: push   block
	//     .wrap
}

const uart_rxOrigin = -1

func uart_rxProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+uart_rxWrapTarget, offset+uart_rxWrap)
	return cfg
}

// uart_tx

const uart_txWrapTarget = 0
const uart_txWrap = 3

var uart_txInstructions = []uint16{
	//     .wrap_target
	0x9fa0, //  0: pull   block           side 1 [7]
	0xf727, //  1: set    x, 7            side 0 [7]
	0x6001, //  2: out    pins, 1
	0x0642, //  3: jmp    x--, 2                 [6]
	//     .wrap
}

const uart_txOrigin = -1

func uart_txProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+uart_txWrapTarget, offset+uart_txWrap)
	cfg.SetSidesetParams(2, true, false)
	return cfg
}
