// Code generated by pioasm; DO NOT EDIT.

package tmc2209

import "seedhammer.com/driver/pio"

// The number of PIO cycles per bit.
const cyclesPerBit = 8

var setYInst = uint32(uart_utilInstructions[0])

// uart

const uartWrapTarget = 8
const uartWrap = 14

const uartErrIRQ = 0
const uartRxIRQ = 1

const uartoffset_transmit = 4

var uartInstructions = []uint16{
	0x86e0, //  0: pull   ifempty block          [6]
	0xf727, //  1: set    x, 7            side 0 [7]
	0x6001, //  2: out    pins, 1
	0x0642, //  3: jmp    x--, 2                 [6]
	0x1880, //  4: jmp    y--, 0          side 1
	0xa642, //  5: nop                           [6]
	0xe080, //  6: set    pindirs, 0
	0xc001, //  7: irq    nowait 1
	//     .wrap_target
	0x2320, //  8: wait   0 pin, 0               [3]
	0xe727, //  9: set    x, 7                   [7]
	0x4001, // 10: in     pins, 1
	0x064a, // 11: jmp    x--, 10                [6]
	0x00c8, // 12: jmp    pin, 8
	0xc000, // 13: irq    nowait 0
	0x20a0, // 14: wait   1 pin, 0
	//     .wrap
}

const uartOrigin = -1

func uartProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+uartWrapTarget, offset+uartWrap)
	cfg.SetSidesetParams(2, true, false)
	return cfg
}

// uart_util

const uart_utilWrapTarget = 0
const uart_utilWrap = 0

var uart_utilInstructions = []uint16{
	//     .wrap_target
	0xe040, //  0: set    y, 0
	//     .wrap
}

const uart_utilOrigin = -1

func uart_utilProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+uart_utilWrapTarget, offset+uart_utilWrap)
	cfg.SetSidesetParams(2, true, false)
	return cfg
}
