// Code generated by seedhammer.com/cmd/vectorfont; DO NOT EDIT.
package sh

import (
	_ "embed"
	"seedhammer.com/font/vector"
	"unsafe"
)

var Font = vector.NewFace(unsafe.Slice(unsafe.StringData(shData), len(shData)))

//go:embed sh.bin
var shData string
