// Code generated by pioasm; DO NOT EDIT.

package mjolnir2

import "seedhammer.com/driver/pio"

const (
	pioCyclesPerStep = 6
)

// mjolnir2

const mjolnir2WrapTarget = 0
const mjolnir2Wrap = 5

const mjolnir2pinBits = 5
const mjolnir2delayBits = 27

var mjolnir2Instructions = []uint16{
	//     .wrap_target
	0x605b, //  0: out    y, 27
	0xb001, //  1: mov    pins, x         side 0
	0x6025, //  2: out    x, 5
	0xb001, //  3: mov    pins, x         side 0
	0x0084, //  4: jmp    y--, 4
	0xa001, //  5: mov    pins, x
	//     .wrap
}

const mjolnir2Origin = -1

func mjolnir2ProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+mjolnir2WrapTarget, offset+mjolnir2Wrap)
	cfg.SetSidesetParams(3, true, false)
	return cfg
}
