// Code generated by seedhammer.com/cmd/bitmapfont; DO NOT EDIT.

package poppins

import (
	_ "embed"
	"seedhammer.com/font/bitmap"
	"unsafe"
)

var Bold20 = bitmap.NewFace(unsafe.Slice(unsafe.StringData(databold20), len(databold20)))

//go:embed bold20.bin
var databold20 string
