// Code generated by seedhammer.com/cmd/bitmapfont; DO NOT EDIT.

package poppins

import (
	_ "embed"
	"seedhammer.com/font/bitmap"
	"unsafe"
)

var Bold25 = bitmap.NewFace(unsafe.Slice(unsafe.StringData(databold25), len(databold25)))

//go:embed bold25.bin
var databold25 string
