// Code generated by seedhammer.com/cmd/bitmapfont; DO NOT EDIT.

package poppins

import (
	_ "embed"
	"seedhammer.com/font/bitmap"
	"unsafe"
)

var Bold16 = bitmap.NewFace(unsafe.Slice(unsafe.StringData(databold16), len(databold16)))

//go:embed bold16.bin
var databold16 string
