// Code generated by seedhammer.com/cmd/bitmapfont; DO NOT EDIT.

package poppins

import (
	_ "embed"
	"seedhammer.com/font/bitmap"
	"unsafe"
)

var Boldprogress45 = bitmap.NewFace(unsafe.Slice(unsafe.StringData(databoldprogress45), len(databoldprogress45)))

//go:embed boldprogress45.bin
var databoldprogress45 string
