// Code generated by gui/assets/gen.go; DO NOT EDIT.
package assets

import (
	_ "embed"
	"unsafe"

	"seedhammer.com/image/alpha4"
	"seedhammer.com/image/ninepatch"
	"seedhammer.com/image/paletted"
)

var (
	ArrowDown = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(ArrowDownData), len(ArrowDownData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 15, MaxY: 9},
	}
	//go:embed arrow-down.bin
	ArrowDownData string

	ArrowLeft = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(ArrowLeftData), len(ArrowLeftData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 9, MaxY: 15},
	}
	//go:embed arrow-left.bin
	ArrowLeftData string

	ArrowRight = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(ArrowRightData), len(ArrowRightData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 9, MaxY: 15},
	}
	//go:embed arrow-right.bin
	ArrowRightData string

	ArrowUp = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(ArrowUpData), len(ArrowUpData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 15, MaxY: 9},
	}
	//go:embed arrow-up.bin
	ArrowUpData string

	ButtonFocused = ninepatch.New(&alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(ButtonFocusedData), len(ButtonFocusedData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 34, MaxY: 25},
	})
	//go:embed button-focused.bin
	ButtonFocusedData string

	CameraCorners = ninepatch.New(&paletted.Image{
		Pix:     unsafe.Slice(unsafe.StringData(CameraCornersData[:3249]), len(CameraCornersData[:3249])),
		Rect:    paletted.Rectangle{MinX: 0, MinY: 0, MaxX: 57, MaxY: 57},
		Palette: paletted.Palette(unsafe.Slice(unsafe.StringData(CameraCornersData[3249:]), len(CameraCornersData[3249:]))),
	})
	//go:embed camera-corners.bin
	CameraCornersData string

	CircleFilled = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(CircleFilledData), len(CircleFilledData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 13, MaxY: 13},
	}
	//go:embed circle-filled.bin
	CircleFilledData string

	Circle = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(CircleData), len(CircleData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 13, MaxY: 13},
	}
	//go:embed circle.bin
	CircleData string

	Hammer = &paletted.Image{
		Pix:     unsafe.Slice(unsafe.StringData(HammerData[:14760]), len(HammerData[:14760])),
		Rect:    paletted.Rectangle{MinX: 0, MinY: 0, MaxX: 120, MaxY: 123},
		Palette: paletted.Palette(unsafe.Slice(unsafe.StringData(HammerData[14760:]), len(HammerData[14760:]))),
	}
	//go:embed hammer.bin
	HammerData string

	IconBack = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconBackData), len(IconBackData)),
		Rect: alpha4.Rectangle{MinX: 8, MinY: 10, MaxX: 26, MaxY: 25},
	}
	//go:embed icon-back.bin
	IconBackData string

	IconBackspace = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconBackspaceData), len(IconBackspaceData)),
		Rect: alpha4.Rectangle{MinX: 7, MinY: 11, MaxX: 27, MaxY: 24},
	}
	//go:embed icon-backspace.bin
	IconBackspaceData string

	IconCheckmark = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconCheckmarkData), len(IconCheckmarkData)),
		Rect: alpha4.Rectangle{MinX: 6, MinY: 8, MaxX: 29, MaxY: 26},
	}
	//go:embed icon-checkmark.bin
	IconCheckmarkData string

	IconDiscard = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconDiscardData), len(IconDiscardData)),
		Rect: alpha4.Rectangle{MinX: 7, MinY: 6, MaxX: 27, MaxY: 29},
	}
	//go:embed icon-discard.bin
	IconDiscardData string

	IconDot = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconDotData), len(IconDotData)),
		Rect: alpha4.Rectangle{MinX: 12, MinY: 12, MaxX: 23, MaxY: 23},
	}
	//go:embed icon-dot.bin
	IconDotData string

	IconEdit = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconEditData), len(IconEditData)),
		Rect: alpha4.Rectangle{MinX: 7, MinY: 7, MaxX: 28, MaxY: 28},
	}
	//go:embed icon-edit.bin
	IconEditData string

	IconFlip = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconFlipData), len(IconFlipData)),
		Rect: alpha4.Rectangle{MinX: 8, MinY: 9, MaxX: 28, MaxY: 27},
	}
	//go:embed icon-flip.bin
	IconFlipData string

	IconHammer = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconHammerData), len(IconHammerData)),
		Rect: alpha4.Rectangle{MinX: 6, MinY: 7, MaxX: 29, MaxY: 29},
	}
	//go:embed icon-hammer.bin
	IconHammerData string

	IconInfo = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconInfoData), len(IconInfoData)),
		Rect: alpha4.Rectangle{MinX: 14, MinY: 8, MaxX: 22, MaxY: 27},
	}
	//go:embed icon-info.bin
	IconInfoData string

	IconLeft = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconLeftData), len(IconLeftData)),
		Rect: alpha4.Rectangle{MinX: 8, MinY: 10, MaxX: 26, MaxY: 25},
	}
	//go:embed icon-left.bin
	IconLeftData string

	IconProgress = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconProgressData), len(IconProgressData)),
		Rect: alpha4.Rectangle{MinX: 6, MinY: 6, MaxX: 29, MaxY: 29},
	}
	//go:embed icon-progress.bin
	IconProgressData string

	IconRight = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconRightData), len(IconRightData)),
		Rect: alpha4.Rectangle{MinX: 9, MinY: 10, MaxX: 27, MaxY: 25},
	}
	//go:embed icon-right.bin
	IconRightData string

	IconSkip = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(IconSkipData), len(IconSkipData)),
		Rect: alpha4.Rectangle{MinX: 8, MinY: 10, MaxX: 26, MaxY: 25},
	}
	//go:embed icon-skip.bin
	IconSkipData string

	KeyActive = ninepatch.New(&alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(KeyActiveData), len(KeyActiveData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 8, MaxY: 14},
	})
	//go:embed key-active.bin
	KeyActiveData string

	KeyBackspace = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(KeyBackspaceData), len(KeyBackspaceData)),
		Rect: alpha4.Rectangle{MinX: 2, MinY: 0, MaxX: 19, MaxY: 11},
	}
	//go:embed key-backspace.bin
	KeyBackspaceData string

	Key = ninepatch.New(&alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(KeyData), len(KeyData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 8, MaxY: 14},
	})
	//go:embed key.bin
	KeyData string

	LogoSmall = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(LogoSmallData), len(LogoSmallData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 21, MaxY: 21},
	}
	//go:embed logo-small.bin
	LogoSmallData string

	NavBtnPrimary = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(NavBtnPrimaryData), len(NavBtnPrimaryData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 35, MaxY: 35},
	}
	//go:embed nav-btn-primary.bin
	NavBtnPrimaryData string

	NavBtnSecondary = &alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(NavBtnSecondaryData), len(NavBtnSecondaryData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 35, MaxY: 35},
	}
	//go:embed nav-btn-secondary.bin
	NavBtnSecondaryData string

	ProgressCircle = &paletted.Image{
		Pix:     unsafe.Slice(unsafe.StringData(ProgressCircleData[:16384]), len(ProgressCircleData[:16384])),
		Rect:    paletted.Rectangle{MinX: 0, MinY: 0, MaxX: 128, MaxY: 128},
		Palette: paletted.Palette(unsafe.Slice(unsafe.StringData(ProgressCircleData[16384:]), len(ProgressCircleData[16384:]))),
	}
	//go:embed progress-circle.bin
	ProgressCircleData string

	Sh02 = &paletted.Image{
		Pix:     unsafe.Slice(unsafe.StringData(Sh02Data[:5720]), len(Sh02Data[:5720])),
		Rect:    paletted.Rectangle{MinX: 1, MinY: 0, MaxX: 89, MaxY: 65},
		Palette: paletted.Palette(unsafe.Slice(unsafe.StringData(Sh02Data[5720:]), len(Sh02Data[5720:]))),
	}
	//go:embed sh02.bin
	Sh02Data string

	WarningBoxBg = ninepatch.New(&alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(WarningBoxBgData), len(WarningBoxBgData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 27, MaxY: 15},
	})
	//go:embed warning-box-bg.bin
	WarningBoxBgData string

	WarningBoxBorder = ninepatch.New(&alpha4.Image{
		Pix:  unsafe.Slice(unsafe.StringData(WarningBoxBorderData), len(WarningBoxBorderData)),
		Rect: alpha4.Rectangle{MinX: 0, MinY: 0, MaxX: 27, MaxY: 15},
	})
	//go:embed warning-box-border.bin
	WarningBoxBorderData string
)
