package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
)

var (
	pkgName   = flag.String("pkg", "", "package name")
	wordsFile = flag.String("f", "wordlist.txt", "path to wordlist file")
)

func main() {
	flag.Parse()
	if err := generate(); err != nil {
		fmt.Fprintf(os.Stderr, "wordlist: %v\n", err)
		os.Exit(1)
	}
}

func generate() error {
	if *pkgName == "" {
		return errors.New("specify package name (-pkg)")
	}
	words, err := os.ReadFile(*wordsFile)
	if err != nil {
		return err
	}
	buf := new(bytes.Buffer)
	fmt.Fprintf(buf, "// Code generated by seedhammer.com/cmd/wordlist; DO NOT EDIT.\n\n")
	fmt.Fprintf(buf, "package %s\n\n", *pkgName)
	fmt.Fprintf(buf, "var index = [...]uint16{")
	idx := 0
	longest, shortest := 0, 1_000_000
	for w := range bytes.SplitSeq(words, []byte("\n")) {
		if len(w) == 0 {
			continue
		}
		fmt.Fprintf(buf, "%d,", idx)
		longest = max(len(w), longest)
		shortest = min(len(w), shortest)
		idx += len(w)
	}
	fmt.Fprintf(buf, "}\n")
	fmt.Fprintf(buf, "const ShortestWord = %d\n\n", shortest)
	fmt.Fprintf(buf, "const LongestWord = %d\n\n", longest)
	fmt.Fprintf(buf, "const words = \"")
	for w := range bytes.SplitSeq(words, []byte("\n")) {
		buf.Write(w)
	}
	fmt.Fprintf(buf, "\"\n\n")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile("wordlist.go", formatted, 0o600)
}
